import test from 'node:test'
import assert from 'node:assert/strict'
import { reconcileOrder, legacyLineKey } from '../src/lib/order-reconcile.ts'

const line = (id, quantity, name='Machine') => ({ id, itemName:name, sku:`SKU-${name}`, zohoItemId:`item-${name}`, rate:10, quantity, pendingQuantity:quantity, woodenPackingRequired:false, dispatchCategory:'machine' })
const order = (lines) => ({ id:'so1', zohoSalesOrderId:'so1', salesOrderNumber:'SO-1', status:'open', customerName:'C', deliveryDate:'2026-01-01', dashboardStatus:'Not Generated', reviewRequired:false, lineItems:lines, machines:lines.flatMap(l=>Array.from({length:l.pendingQuantity},(_,i)=>({ id:`so1-${l.id}-${i+1}`, unitNumber:i+1, serialNumber:'', qrToken:'', orderId:'so1', lineItemId:l.id,itemName:l.itemName,sku:l.sku,customerName:'C',salesOrderNumber:'SO-1',deliveryDate:'2026-01-01',status:'Not Generated',selectedForBatch:false,woodenPacking:'Not Required',qrPasted:false,qcDone:false,mediaPhotos:0,mediaVideos:0 }))) })

test('removal/addition/reorder and repeat are safe',()=>{ const local=order([line('a',2,'A'),line('b',1,'B')]); local.machines[0].serialNumber='99'; const remote=order([line('b',1,'B'),line('c',1,'C')]); const r=reconcileOrder(local,remote,new Set([local.machines[0].id]),'now'); assert.deepEqual(r.diff.removed,['a']); assert.deepEqual(r.diff.added,['c']); assert.equal(r.order.machines.some(m=>m.lineItemId==='a'),false); assert.equal(r.order.retiredMachines[0].serialNumber,'99'); assert.equal(r.order.machines.find(m=>m.lineItemId==='b').id,'so1-b-1'); const again=reconcileOrder(r.order,remote); assert.equal(again.changed,false); assert.equal(again.order.machines.length,2) })
test('quantity reduction removes highest unprocessed and retains processed excess',()=>{ const local=order([line('a',5)]); local.machines[4].serialNumber='processed'; const r=reconcileOrder(local,order([line('a',3)])); assert.deepEqual(r.order.machines.map(m=>m.id),['so1-a-1','so1-a-2','so1-a-3']); assert.equal(r.order.retiredMachines[0].id,'so1-a-5'); assert.equal(r.order.retiredMachines[0].serialNumber,'processed') })
test('quantity increase adds clean delta without renumbering',()=>{ const local=order([line('a',3)]); local.machines[0].serialNumber='keep'; const r=reconcileOrder(local,order([line('a',5)])); assert.equal(r.order.machines[0].serialNumber,'keep'); assert.deepEqual(r.order.machines.slice(3).map(m=>m.id),['so1-a-4','so1-a-5']); assert.ok(r.order.machines.slice(3).every(m=>!m.serialNumber&&!m.qrToken)) })
test('legacy matching is conservative and not array-index based',()=>{ const a=line('line-0',1,'A'), b=line('line-1',1,'B'); assert.notEqual(legacyLineKey(a),legacyLineKey(b)); const r=reconcileOrder(order([a,b]),order([{...b,id:'line-0'},{...a,id:'line-1'}])); assert.equal(r.order.machines.find(m=>m.lineItemId==='line-0').itemName,'B'); assert.equal(r.order.machines.find(m=>m.lineItemId==='line-1').itemName,'A') })
