import { test } from 'node:test'
import assert from 'node:assert/strict'
import { sheetSuppliers, applySheetSuppliers, preserveSheetSuppliers } from '../src/lib/serial-sheet-suppliers.ts'
const store = () => ({ orders: { o: { salesOrderId:'o', status:'processed', machines:{m:{machineUnitId:'m',serialNumber:'001',vendor:'Able',qrStatus:'generated',zohoBackupStatus:'synced'}},processedOrder:{machines:[{id:'m',serialNumber:'001',vendor:'Able'}]} } }, serialCounter:42 })
const row=(index,serial,make)=>({row_index:index,row_details:[{column_index:1,content:serial},{column_index:2,content:make}]})
const rows=()=>[row(1,'Serial No.','Make '),row(2,'001','K S ')]
test('already synced correction updates workflow + processed snapshot; idempotent',()=>{const s=store();const p=sheetSuppliers(rows(),s);assert.equal(applySheetSuppliers(s,p),2);assert.equal(s.orders.o.machines.m.vendor,'K S');assert.equal(s.orders.o.processedOrder.machines[0].vendor,'K S');assert.equal(s.serialCounter,42);assert.equal(s.orders.o.machines.m.zohoBackupStatus,'synced');assert.equal(applySheetSuppliers(s,p),0)})
test('blank never erases; exact serial no numeric normalization',()=>{const s=store();assert.deepEqual(sheetSuppliers([row(1,'Serial No.','Make'),row(2,'001','')],s),[]);applySheetSuppliers(s,[{serial:'1',vendor:'Other'}]);assert.equal(s.orders.o.machines.m.vendor,'Able')})
test('duplicates on either side skipped',()=>{const s=store();assert.deepEqual(sheetSuppliers([...rows(),row(3,'001','K S')],s),[]);s.orders.o.machines.n={...s.orders.o.machines.m,machineUnitId:'n'};assert.deepEqual(sheetSuppliers(rows(),s),[]);assert.equal(applySheetSuppliers(s,[{serial:'001',vendor:'K S'}]),0)})
test('concurrent stale workflow saves preserve authoritative supplier and new status',()=>{const s=store();applySheetSuppliers(s,sheetSuppliers(rows(),s));const next=store().orders.o;next.machines.m.dispatchedAt='now';const merged=preserveSheetSuppliers(next,s.orders.o);assert.equal(merged.machines.m.vendor,'K S');assert.equal(merged.processedOrder.machines[0].vendor,'K S');assert.equal(merged.machines.m.dispatchedAt,'now')})
test('later Sheet edits replace earlier authoritative supplier',()=>{const s=store();applySheetSuppliers(s,sheetSuppliers(rows(),s));applySheetSuppliers(s,sheetSuppliers([rows()[0],row(2,'001','New Supplier')],s));assert.equal(s.orders.o.machines.m.sheetVendor,'New Supplier')})
