import { DashboardShell, Badge } from '@/components/DashboardShell'
import { machines, orders } from '@/lib/mock-data'

const tabs = ['QR Pending','QR Generated','QR Printed','Wooden Packing','Ready for Packaging','Packing Done','Media Pending','Vehicle Pending','Dispatched','Review Required']

export default function Home() {
  const readyForDispatch = machines.filter((m) => m.mediaPhotos >= 2 && m.mediaVideos >= 1 && m.status !== 'Dispatched').length
  return <DashboardShell>
    <header className="top"><div><div className="eyebrow">BSM India internal dashboard</div><h1 className="h1">Dispatch, Serial Number, QR Label & Machine Passport</h1><p className="muted">Zoho Sales Order → Serial + QR → Packing → Media Proof → Vehicle → Warranty → Passport.</p></div><button className="btn red">Sync Zoho Now</button></header>
    <section className="grid stats"><div className="card stat"><span className="muted">Zoho Orders</span><b>{orders.length}</b></div><div className="card stat"><span className="muted">Machine Units</span><b>{machines.length}</b></div><div className="card stat"><span className="muted">Ready Dispatch</span><b>{readyForDispatch}</b></div><div className="card stat"><span className="muted">Review Required</span><b>{orders.filter(o=>o.reviewRequired).length}</b></div></section>
    <section id="orders" className="card"><h2>Orders</h2><div className="tabs">{tabs.map(t=><span className="pill" key={t}>{t}</span>)}</div><table className="table"><thead><tr><th>SO</th><th>Customer</th><th>Delivery</th><th>Units</th><th>Status</th><th>Warning</th><th>Action</th></tr></thead><tbody>{orders.map(o=><tr key={o.id}><td><strong>{o.salesOrderNumber}</strong></td><td>{o.customerName}</td><td>{o.deliveryDate}</td><td>{o.machines.length}</td><td><Badge tone={o.reviewRequired?'red':o.dashboardStatus==='Dispatched'?'green':'blue'}>{o.dashboardStatus}</Badge></td><td>{o.reviewRequired ? <Badge tone="red">Zoho changed after QR</Badge> : <span className="muted">Clear</span>}</td><td><a className="btn light" href={`/orders/${o.id}`}>Open</a></td></tr>)}</tbody></table></section>
    <section className="grid two" style={{marginTop:16}}><div className="card" id="qr-&-serial-generation"><h2>QR & Serial Generation</h2><p className="muted">Backend-only serials with FY prefix, transaction locking, idempotency, QR token URL, print history and reprint audit.</p><div className="label-preview" style={{marginTop:16}}><strong>BSM</strong><div className="qrbox"/><b>Serial: 262700001</b><span>SO-1001 · Belt Conveyor</span><span>Arihant Foods Pvt Ltd</span></div></div><div className="card" id="sync-monitor"><h2>Sync Monitor</h2><div className="machine"><div className="machine-row"><span>Zoho webhook</span><Badge tone="green">Ready</Badge></div><div className="machine-row"><span>Backup sync every 10–15 min</span><Badge>Planned</Badge></div><div className="machine-row"><span>WorkDrive folder upload</span><Badge tone="amber">Fallback supported</Badge></div></div></div></section>
    <section className="grid three" style={{marginTop:16}}><Module title="Wooden Packing" text="Auto-created from Zoho item custom field. Pending, Ordered, In Progress, Completed, Issue/Rework."/><Module title="Media Proof" text="Minimum 2 photos and 1 video before dispatch. Stores WorkDrive metadata, not video blobs."/><Module title="Vehicle / Dispatch" text="Manual transporter entry, LR/docket, loading photo, dispatch lock, warranty start date."/></section>
  </DashboardShell>
}

function Module({title,text}:{title:string;text:string}){return <div className="card"><h2>{title}</h2><p className="muted">{text}</p></div>}
