'use client'
import {useCallback,useEffect,useRef,useState} from 'react'
import type {PublicDatabaseRow} from '@/lib/public-database-snapshot'
type Result={items:PublicDatabaseRow[];page:number;pages:number;total:number;snapshotVersion:string;generatedAt:string}
type Detail={id:string;salesOrderNumber:string;customerName:string;salesperson:string;shippingAddress:string;deliveryDate:string;warrantyDate:string;status:{lifecycleLabel:string;mediaLabel:string};machines:Array<{id:string;itemName:string;serialNumber:string;vendor:string}>;shipment?:Record<string,string>;media:Array<{id:string;kind:string;name?:string;url:string}>;snapshotVersion:string}
export function PublicDatabaseClient(){const[q,setQ]=useState('');const[filter,setFilter]=useState('all');const[page,setPage]=useState(1);const[data,setData]=useState<Result>();const[loading,setLoading]=useState(true);const[error,setError]=useState('');const[detail,setDetail]=useState<Detail>();const[detailLoading,setDetailLoading]=useState(false);const seq=useRef(0)
 const load=useCallback(async()=>{const n=++seq.current;const c=new AbortController();setLoading(true);setError('');try{const r=await fetch(`/api/public/database/search?q=${encodeURIComponent(q)}&filter=${filter}&page=${page}&limit=25`,{signal:c.signal});if(!r.ok)throw new Error();const j=await r.json();if(n===seq.current)setData(j)}catch{if(n===seq.current)setError('Database is temporarily unavailable. Please retry.')}finally{if(n===seq.current)setLoading(false)}return()=>c.abort()},[q,filter,page]);useEffect(()=>{const t=setTimeout(load,225);return()=>clearTimeout(t)},[load])
 async function open(row:PublicDatabaseRow){setDetailLoading(true);setError('');try{let r=await fetch(`/api/public/database/orders/${encodeURIComponent(row.id)}?snapshotVersion=${data?.snapshotVersion||''}`,{cache:'no-store'});if(r.status===409){await load();r=await fetch(`/api/public/database/orders/${encodeURIComponent(row.id)}`,{cache:'no-store'})}if(!r.ok)throw new Error();setDetail(await r.json())}catch{setError('Record details could not be loaded. Retry.')}finally{setDetailLoading(false)}}
 return <div className="public-database-view"><section className="card search-panel database-search-panel"><div className="database-search-input-wrap"><input aria-label="Search database" placeholder="Search SO, serial, customer…" value={q} onChange={e=>{setQ(e.target.value);setPage(1)}}/>{q&&<button className="database-clear-x" onClick={()=>setQ('')}>×</button>}</div><select value={filter} onChange={e=>{setFilter(e.target.value);setPage(1)}} aria-label="Filter database records"><option value="all">All Records</option><option value="pending">Pending</option><option value="submitted">Media Submitted</option><option value="closed">Closed</option><option value="builty">Builty Uploaded</option></select></section>
 {error&&<section className="card"><p>{error}</p><button className="btn" onClick={()=>load()}>Retry</button></section>}{loading&&!data&&<section className="card"><p className="muted">Loading database…</p></section>}
 {data&&<section className="card database-list-card"><div className="database-list-head"><h2>Database</h2><span className="muted">{data.total} records · Updated {new Date(data.generatedAt).toLocaleString('en-IN')}</span></div><div className="table-wrap"><table className="table"><thead><tr><th>SO</th><th>Customer</th><th>Units</th><th>Warranty Valid Till</th><th>Media</th><th>Action</th></tr></thead><tbody>{data.items.map(r=><tr key={r.id}><td><strong>{r.salesOrderNumber}</strong></td><td>{r.customerName}{r.builtyUploaded&&<small className="database-builty-chip"> Builty Uploaded</small>}</td><td>{r.units}</td><td>{r.warrantyEnd}</td><td>{r.mediaLabel}</td><td><button className="btn light" onClick={()=>open(r)}>View</button></td></tr>)}</tbody></table></div>{!data.items.length&&<p className="muted">No matching records.</p>}<div className="database-pagination"><button className="btn light" disabled={page<=1} onClick={()=>setPage(p=>p-1)}>Previous</button><span>Page {data.page} of {Math.max(1,data.pages)}</span><button className="btn light" disabled={page>=data.pages} onClick={()=>setPage(p=>p+1)}>Next</button></div></section>}{detailLoading&&<div className="modal-backdrop"><section className="order-modal card">Loading record…</section></div>}{detail&&<div className="modal-backdrop" role="dialog" aria-modal="true"><section className="order-modal card"><div className="modal-head"><div><h1>{detail.salesOrderNumber}</h1><p>{detail.customerName}</p></div><button className="drawer-close" onClick={()=>setDetail(undefined)}>×</button></div><div className="grid two details-grid"><Info k="Stage" v={detail.status.lifecycleLabel}/><Info k="Media" v={detail.status.mediaLabel}/><Info k="Customer" v={detail.customerName}/><Info k="Salesperson" v={detail.salesperson||'—'}/><Info k="Address" v={detail.shippingAddress||'—'}/><Info k="Delivery" v={detail.deliveryDate||'—'}/></div><h2>Units & Media</h2>{detail.machines.map(m=><div className="info-tile" key={m.id}><strong>{m.itemName}</strong><span>Serial: {m.serialNumber||'—'} · Vendor: {m.vendor||'—'}</span></div>)}<div className="database-video-actions">{detail.media.map((m,i)=><a key={m.id} className="btn light" href={m.url} target="_blank" rel="noreferrer">View {m.kind} {i+1}</a>)}</div></section></div>}</div>}
function Info({k,v}:{k:string;v:string}){return <div className="info-tile"><span>{k}</span><strong>{v}</strong></div>}
